volumes:
  postgres_data:

services:
  kafka:
    image: apache/kafka:4.2.0
    container_name: candle-stack-kafka
    hostname: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    container_name: candle-stack-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: candlestack
      POSTGRES_USER: candlestack_user
      POSTGRES_PASSWORD: candlestack_password
    command:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U candlestack_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingestion-service:
    build:
      context: .
      dockerfile: ingestion-service/Dockerfile
    container_name: candle-stack-ingestion-service
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 8081
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CANDLESTACK_KAFKA_TOPICS_MARKET_TRADES: market-trades
    ports:
      - "8081:8081"
    restart: unless-stopped

  generator-service:
    build:
      context: .
      dockerfile: generator-service/Dockerfile
    container_name: candle-stack-generator-service
    depends_on:
      - ingestion-service
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  processing-service:
    build:
      context: .
      dockerfile: processing-service/Dockerfile
    container_name: candle-stack-processing-service
    depends_on:
      - kafka
      - postgres
    environment:
      SERVER_PORT: 8082
      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: processing-service
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      CANDLESTACK_KAFKA_TOPICS_MARKET_TRADES: market-trades
      # Postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/candlestack
      SPRING_DATASOURCE_USERNAME: candlestack_user
      SPRING_DATASOURCE_PASSWORD: candlestack_password
      
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      SPRING_FLYWAY_ENABLED: true

    ports:
      - "8082:8082"
    restart: unless-stopped


